name: Generator

on:
  push:
    branches:
      - main
  watch:
    types: [started]
  schedule:
    - cron: '0 * * * *'
env:
  GITHUB_NAME: ${{ secrets.GH_NAME }} # 你的github昵称
  GITHUB_EMAIL: ${{ secrets.GH_EMAIL }} # 你的github邮箱
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # github token

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.8
        
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        
    - name: Run Generator
      run: |
        python generator/v2.py
    
    - run: |
        git config user.name github-actions[bot]
        git config user.email github-actions@noreply.github.com
        
    - name: Commit & Push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'output'
        commit-message: 'Generate Json'
        force-push: 'true'
        rebase: 'true'
        name: github-actions[bot]
        email: github-actions@noreply.github.com
        
    - name: keep alive
      uses: gautamkrishnar/keepalive-workflow@master # keep workflows from being suspended when no commit for a long time
