name: Generator

on:
  push:
    branches:
      - main
  watch:
    types: [started]
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run Generator
      run: |
        python generator/v2.py
    - run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git init api-gh-json
    - name: Commit & Push
      uses: action-x/commit@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'output'
        commit-message: 'Generate Json'
        force-push: 'true'
        name: github-actions[bot]
        email: github-actions[bot]@users.noreply.github.com
