name: Generator

on:
  push:
    branches:
      - main
  watch:
    types: [started]
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        node-version: '14'
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run Generator
      run: |
        python generator/v2.py
    - run: |
        git config user.name ThatCoders
        git config user.email nepenthic@163.com
    - name: Commit & Push
      uses: action-x/commit@v2.9
      with:
        node-version: '14'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'output'
        commit-message: 'Generate Json'
        force-push: 'true'
        name: ThatCoders
        email: nepenthic@163.com
